name: trip_app_nativeapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  firebase_auth: ^4.6.3
  firebase_auth_mocks: ^0.11.0
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_gen: ^5.3.1
  flutter_hooks: ^0.20.0
  flutter_line_sdk: ^2.3.3
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^5.0.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  lottie: ^2.5.0
  mockito: ^5.4.2
  mocktail: ^0.3.0
  nil: ^1.1.1
  riverpod_annotation: ^2.1.1
  roggle: ^0.3.0
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  google_sign_in_mocks: ^0.3.0
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - .env.local
    - .env.prism
    - .env.prod

flutter_gen:
  output: lib/core/gen
