name: trip_app_nativeapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^3.11.0
  firebase_auth_mocks: ^0.8.6
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_gen: ^4.3.0
  flutter_hooks: ^0.18.5+1
  flutter_line_sdk: ^2.3.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  lottie: ^1.4.3
  nil: ^1.1.1
  roggle: ^0.2.1+1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  envied_generator: ^0.2.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - .prod.env
    - .dev.env
