name: Flutter CI

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@121a924f6e02514871f0d3507fbac542ced8cb4b

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install custom_lint
        run: dart pub global activate custom_lint

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@5f7e9a8065363343c808346284ea23507d07157c
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .dev.env

      - name: Make prod envfile
        uses: SpicyPizza/create-envfile@5f7e9a8065363343c808346284ea23507d07157c
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .prod.env

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run riverpod_lint
        run: custom_lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@121a924f6e02514871f0d3507fbac542ced8cb4b

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install custom_lint
        run: dart pub global activate custom_lint

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@5f7e9a8065363343c808346284ea23507d07157c
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .dev.env

      - name: Make prod envfile
        uses: SpicyPizza/create-envfile@5f7e9a8065363343c808346284ea23507d07157c
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .prod.env
      - name: Run Flutter Test
        run: flutter test --machine --coverage > test-report.log

      - name: Report Test
        uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203
        if: always()
        with:
          name: Flutter Test Report
          path: test-report.log
          reporter: flutter-json

      # Codecov に結果を送信
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@7f20bd4c4151750a1d013be0901b7e35a46c2aad
      #   with:
      #     file: coverage/lcov.info
      #     fail_ci_if_error: true
      #     flags: unittests
      #     verbose: true
      #
