name: Flutter CI

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main

jobs:
  ci:
    name: Flutter CI
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@e91317131a2da710b9cd9b7a24f2c0ade9eeb61d

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Make dev envfile
        uses: SpicyPizza/create-envfile@041383d6577d09916e24632ef274f18ec2909b4f
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .dev.env

      - name: Make prod envfile
        uses: SpicyPizza/create-envfile@041383d6577d09916e24632ef274f18ec2909b4f
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: '123456abcdef'
          envkey_LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          envkey_TRIPAPP_API_URL: ${{ secrets.TRIPAPP_API_URL }}
          envkey_TRIPAPP_API_PORT: ${{ secrets.TRIPAPP_API_PORT }}
          file_name: .prod.env

      - name: Install custom_lint
        run: dart pub global activate custom_lint

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Cache Flutter dependencies
        uses: actions/cache@77eb7eb198e1383478da175398ace52efd5464d0
        with:
          path: |
            .dart_tool/package_config.json
            .pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run riverpod_lint
        run: custom_lint

      - name: Run Flutter Test
        run: flutter test --machine --coverage > test-report.log

      - name: Report Test
        uses: dorny/test-reporter@19aaf9016ed662cee850ab18a3224cfdada01699
        if: always()
        with:
          name: Flutter Test Report
          path: test-report.log
          reporter: flutter-json
